### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by madhall** [kest01/android-calendar-sync#1]
Hi Konstantin,

this has been incredibly helpful, thanks for sharing.

I had an issue though,

1. can this code be used to sync from Google calendar to firebase
2. how to achieve a full sync the first time around, I understood that you are syncing a 3 day period... 

thanks for any clarifications in advance

**Comment by kest01** [comment]
Hi madhall,

1. Sorry, I'm not a mobile app developer, I'm know nothing about firebase. This code can help syncronize any calendars which is avialable on Android device.
2. For example, you can store boolean flag in SharedPreferences that will determine whether this is first sync or not. Also you can change 3 days to 30 or whatever you need. It should work fast enough because uses only local data.
